services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=development
      - MONGO_URI=mongodb+srv://roshan:l5ppwgpgN5MryQAk@fifa-tracker.eqz1vaw.mongodb.net/fifa_rivalry
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - LOG_LEVEL=INFO
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
