services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-43200}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
