services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-43200}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - app-network
    depends_on:
      - metabase

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase_data:/metabase-data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  metabase_data:
