services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
